### ISSUE TITLE
Artifact versions with '+' character not supported

### ISSUE THREAD

**Issue by joschi** [maxcellent/javadoc.io#14]
First of all thank you so much for building and running an immensely useful service such as javadoc.io! 😄

We're using semantic versioning for our artifacts (at least we're trying to), which means that the version could contain a '+' character to separate build metadata from the rest of the version string (also see https://semver.org/#spec-item-10).

It looks like javadoc.io currently doesn't support artifacts which contain a '+'  character in their version.

### Failing

* https://javadoc.io/doc/org.graylog.jest/jest/2.4.12+jackson
* https://javadoc.io/doc/org.graylog.jest/jest/2.4.12%2Bjackson

### Working

* https://javadoc.io/doc/org.graylog.jest/jest/2.4.5

----

Interesting enough, this seems to be an encoding issue, too:

### Failing

* https://static.javadoc.io/org.graylog.jest/jest/2.4.12+jackson/index.html

### Working

* https://static.javadoc.io/org.graylog.jest/jest/2.4.12%2Bjackson/index.html

**Comment by sirocchj** [comment]
Likewise, using something like [sbt-dynver](https://github.com/dwijnand/sbt-dynver) for git commits+tags based versioning leads to the same issue, see https://javadoc.io/doc/io.laserdisc/laserdisc-core_2.12/0.1.0+3-fedc3f12

**Comment by Atry** [comment]
This bug also affect `latest` URLs.

For example, https://javadoc.io/page/com.thoughtworks.dsl/dsl_2.12/latest/com/thoughtworks/dsl/index.html redirects to https://static.javadoc.io/com.thoughtworks.dsl/dsl_2.12/1.0.0-RC22+36-6a0631d6/com/thoughtworks/dsl/index.html, which is a broken URL. The proper URL should be https://static.javadoc.io/com.thoughtworks.dsl/dsl_2.12/1.0.0-RC22%2B36-6a0631d6/com/thoughtworks/dsl/index.html.

**Comment by maxcellent** [comment]
fixed and deployed

**Comment by Atry** [comment]
This bug is not resolved.

https://javadoc.io/page/com.thoughtworks.binding/latestevent_sjs0.6_2.11/latest/com/thoughtworks/binding/LatestEvent.html is still a broken URL

**Comment by maxcellent** [comment]
ah, not aware there is another one. Fixed.
